// lib/models/currency_model.dart

class Currency {
  final String code;   // كود العملة (مثلاً: USD, SAR)
  final String name;   // اسم العملة بالعربي
  final String symbol; // الرمز (لو غير متوفر نحط الكود نفسه)
  final String flag;   // علم الدولة (إيموجي)

  const Currency({
    required this.code,
    required this.name,
    required this.symbol,
    required this.flag,
  });

  /// القائمة الرئيسية لكل العملات المدعومة في التطبيق
  static List<Currency> getCurrencies() {
    return const [

      // 🔹 بعض العملات الأساسية (لو كانت موجودة عندك قبل) + دعم إضافي
      Currency(
        code: 'USD',
        name: 'الدولار الأمريكي',
        symbol: '\$',
        flag: '🇺🇸',
      ),
      Currency(
        code: 'GBP',
        name: 'الجنيه الإسترليني',
        symbol: '£',
        flag: '🇬🇧',
      ),

      // 🌍 العملات التي طلبت إضافتها:

      Currency(
        code: 'AED',
        name: 'الدرهم الإماراتي',
        symbol: 'د.إ',
        flag: '🇦🇪',
      ),
      Currency(
        code: 'AFN',
        name: 'الأفغاني',
        symbol: 'AFN',
        flag: '🇦🇫',
      ),
      Currency(
        code: 'ALL',
        name: 'اللك',
        symbol: 'ALL',
        flag: '🇦🇱',
      ),
      Currency(
        code: 'AMD',
        name: 'الدرام الأرميني',
        symbol: 'AMD',
        flag: '🇦🇲',
      ),
      Currency(
        code: 'ANG',
        name: 'غيلدر الأنتيل',
        symbol: 'ANG',
        flag: '🇳🇱',
      ),
      Currency(
        code: 'AOA',
        name: 'الكوانزا',
        symbol: 'AOA',
        flag: '🇦🇴',
      ),
      Currency(
        code: 'ARS',
        name: 'البيزو الأرجنتيني',
        symbol: 'ARS',
        flag: '🇦🇷',
      ),
      Currency(
        code: 'AUD',
        name: 'الدولار الأسترالي',
        symbol: 'A\$',
        flag: '🇦🇺',
      ),
      Currency(
        code: 'AZN',
        name: 'المنات الأذربيجاني',
        symbol: 'AZN',
        flag: '🇦🇿',
      ),
      Currency(
        code: 'BBD',
        name: 'دولار بربادوس',
        symbol: 'BBD',
        flag: '🇧🇧',
      ),
      Currency(
        code: 'BDT',
        name: 'التاكا',
        symbol: 'BDT',
        flag: '🇧🇩',
      ),
      Currency(
        code: 'BGN',
        name: 'الليفا البلغاري',
        symbol: 'BGN',
        flag: '🇧🇬',
      ),
      Currency(
        code: 'BHD',
        name: 'الدينار البحريني',
        symbol: 'د.ب',
        flag: '🇧🇭',
      ),
      Currency(
        code: 'BIF',
        name: 'الفرنك البوروندي',
        symbol: 'BIF',
        flag: '🇧🇮',
      ),
      Currency(
        code: 'BND',
        name: 'دولار بروناي',
        symbol: 'BND',
        flag: '🇧🇳',
      ),
      Currency(
        code: 'BOB',
        name: 'البوليفيانو',
        symbol: 'BOB',
        flag: '🇧🇴',
      ),
      Currency(
        code: 'BRL',
        name: 'الريال البرازيلي',
        symbol: 'R\$',
        flag: '🇧🇷',
      ),
      Currency(
        code: 'BRLT',
        name: 'الريال البرازيلي التاريخي',
        symbol: 'BRLT',
        flag: '🇧🇷',
      ),
      Currency(
        code: 'BSD',
        name: 'دولار الباهاما',
        symbol: 'BSD',
        flag: '🇧🇸',
      ),
      Currency(
        code: 'BWP',
        name: 'البولا',
        symbol: 'BWP',
        flag: '🇧🇼',
      ),
      Currency(
        code: 'BYN',
        name: 'الروبل البيلاروسي',
        symbol: 'BYN',
        flag: '🇧🇾',
      ),
      Currency(
        code: 'BZD',
        name: 'دولار بليز',
        symbol: 'BZD',
        flag: '🇧🇿',
      ),
      Currency(
        code: 'CAD',
        name: 'الدولار الكندي',
        symbol: 'C\$',
        flag: '🇨🇦',
      ),
      Currency(
        code: 'CHF',
        name: 'الفرنك السويسري',
        symbol: 'CHF',
        flag: '🇨🇭',
      ),
      Currency(
        code: 'CLP',
        name: 'البيزو التشيلي',
        symbol: 'CLP',
        flag: '🇨🇱',
      ),
      Currency(
        code: 'CNY',
        name: 'اليوان الصيني (الرنمينبي)',
        symbol: '¥',
        flag: '🇨🇳',
      ),
      Currency(
        code: 'CNH',
        name: 'اليوان الصيني بسعر صرف هونج كونج',
        symbol: 'CNH',
        flag: '🇨🇳',
      ),
      Currency(
        code: 'COP',
        name: 'البيزو الكولومبي',
        symbol: 'COP',
        flag: '🇨🇴',
      ),
      Currency(
        code: 'CRC',
        name: 'الكولون الكوستاريكي',
        symbol: 'CRC',
        flag: '🇨🇷',
      ),
      Currency(
        code: 'CUP',
        name: 'البيزو الكوبي',
        symbol: 'CUP',
        flag: '🇨🇺',
      ),
      Currency(
        code: 'CZK',
        name: 'الكرونا التشيكية',
        symbol: 'CZK',
        flag: '🇨🇿',
      ),
      Currency(
        code: 'DJF',
        name: 'الفرنك الجيبوتي',
        symbol: 'DJF',
        flag: '🇩🇯',
      ),
      Currency(
        code: 'DKK',
        name: 'الكرونا الدانماركية',
        symbol: 'DKK',
        flag: '🇩🇰',
      ),
      Currency(
        code: 'DOP',
        name: 'البيزو الدومينيكاني',
        symbol: 'DOP',
        flag: '🇩🇴',
      ),
      Currency(
        code: 'DZD',
        name: 'الدينار الجزائري',
        symbol: 'د.ج',
        flag: '🇩🇿',
      ),
      Currency(
        code: 'EGP',
        name: 'الجنيه المصري',
        symbol: 'ج.م',
        flag: '🇪🇬',
      ),
      Currency(
        code: 'ETB',
        name: 'البر الإثيوبي',
        symbol: 'ETB',
        flag: '🇪🇹',
      ),
      Currency(
        code: 'EUR',
        name: 'اليورو',
        symbol: '€',
        flag: '🇪🇺',
      ),
      Currency(
        code: 'FJD',
        name: 'دولار فيجي',
        symbol: 'FJD',
        flag: '🇫🇯',
      ),
      Currency(
        code: 'GEL',
        name: 'اللاري الجورجي',
        symbol: 'GEL',
        flag: '🇬🇪',
      ),
      Currency(
        code: 'GHS',
        name: 'السيدي الغاني',
        symbol: 'GHS',
        flag: '🇬🇭',
      ),
      Currency(
        code: 'GMD',
        name: 'الدالاسي الجامبي',
        symbol: 'GMD',
        flag: '🇬🇲',
      ),
      Currency(
        code: 'GNF',
        name: 'الفرنك الغيني',
        symbol: 'GNF',
        flag: '🇬🇳',
      ),
      Currency(
        code: 'GTQ',
        name: 'الكيتزال',
        symbol: 'GTQ',
        flag: '🇬🇹',
      ),
      Currency(
        code: 'HKD',
        name: 'دولار هونج كونج',
        symbol: 'HK\$',
        flag: '🇭🇰',
      ),
      Currency(
        code: 'HNL',
        name: 'اللمبيرا الهندوراسية',
        symbol: 'HNL',
        flag: '🇭🇳',
      ),
      Currency(
        code: 'HTG',
        name: 'الجورد الهايتي',
        symbol: 'HTG',
        flag: '🇭🇹',
      ),
      Currency(
        code: 'HUF',
        name: 'الفورنت المجري',
        symbol: 'HUF',
        flag: '🇭🇺',
      ),
      Currency(
        code: 'IDR',
        name: 'الروبية الإندونيسية',
        symbol: 'IDR',
        flag: '🇮🇩',
      ),
      Currency(
        code: 'ILS',
        name: 'الشيكل الإسرائيلي',
        symbol: '₪',
        flag: '🇮🇱',
      ),
      Currency(
        code: 'INR',
        name: 'الروبية الهندية',
        symbol: '₹',
        flag: '🇮🇳',
      ),
      Currency(
        code: 'IQD',
        name: 'الدينار العراقي',
        symbol: 'د.ع',
        flag: '🇮🇶',
      ),
      Currency(
        code: 'IRR',
        name: 'الريال الإيراني',
        symbol: '﷼',
        flag: '🇮🇷',
      ),
      Currency(
        code: 'ISK',
        name: 'الكرونا الآيسلندية',
        symbol: 'ISK',
        flag: '🇮🇸',
      ),
      Currency(
        code: 'JMD',
        name: 'دولار جامايكا',
        symbol: 'JMD',
        flag: '🇯🇲',
      ),
      Currency(
        code: 'JOD',
        name: 'الدينار الأردني',
        symbol: 'د.أ',
        flag: '🇯🇴',
      ),
      Currency(
        code: 'JPY',
        name: 'الين الياباني',
        symbol: '¥',
        flag: '🇯🇵',
      ),
      Currency(
        code: 'KES',
        name: 'الشلن الكيني',
        symbol: 'KES',
        flag: '🇰🇪',
      ),
      Currency(
        code: 'KGS',
        name: 'السوم القرغيزي',
        symbol: 'KGS',
        flag: '🇰🇬',
      ),
      Currency(
        code: 'KHY',
        name: 'الريال الكمبودي',
        symbol: 'KHY',
        flag: '🇰🇭',
      ),
      Currency(
        code: 'KMF',
        name: 'الفرنك القمري',
        symbol: 'KMF',
        flag: '🇰🇲',
      ),
      Currency(
        code: 'KRW',
        name: 'الوون الكوري الجنوبي',
        symbol: '₩',
        flag: '🇰🇷',
      ),
      Currency(
        code: 'KWD',
        name: 'الدينار الكويتي',
        symbol: 'د.ك',
        flag: '🇰🇼',
      ),
      Currency(
        code: 'KZT',
        name: 'التنج الكازاخي',
        symbol: 'KZT',
        flag: '🇰🇿',
      ),
      Currency(
        code: 'LAK',
        name: 'اللاو اللاوسي',
        symbol: 'LAK',
        flag: '🇱🇦',
      ),
      Currency(
        code: 'LBP',
        name: 'الجنيه اللبناني',
        symbol: 'ل.ل',
        flag: '🇱🇧',
      ),
      Currency(
        code: 'LKR',
        name: 'الروبية السريلانكية',
        symbol: 'LKR',
        flag: '🇱🇰',
      ),
      Currency(
        code: 'LSL',
        name: 'اللوتي',
        symbol: 'LSL',
        flag: '🇱🇸',
      ),
      Currency(
        code: 'LYD',
        name: 'الدينار الليبي',
        symbol: 'د.ل',
        flag: '🇱🇾',
      ),
      Currency(
        code: 'MAD',
        name: 'الدرهم المغربي',
        symbol: 'د.م',
        flag: '🇲🇦',
      ),
      Currency(
        code: 'MDL',
        name: 'ليو مولدافي',
        symbol: 'MDL',
        flag: '🇲🇩',
      ),
      Currency(
        code: 'MGA',
        name: 'الأريري الملغاشي',
        symbol: 'MGA',
        flag: '🇲🇬',
      ),
      Currency(
        code: 'MKD',
        name: 'الدينار المقدوني',
        symbol: 'MKD',
        flag: '🇲🇰',
      ),
      Currency(
        code: 'MMK',
        name: 'الكيات الميانماري',
        symbol: 'MMK',
        flag: '🇲🇲',
      ),
      Currency(
        code: 'MNT',
        name: 'الثغري المنغولي',
        symbol: 'MNT',
        flag: '🇲🇳',
      ),
      Currency(
        code: 'MOP',
        name: 'الباتاكا ماكاوية',
        symbol: 'MOP',
        flag: '🇲🇴',
      ),
      Currency(
        code: 'MRO',
        name: 'الأوقية الموريتانية',
        symbol: 'MRO',
        flag: '🇲🇷',
      ),
      Currency(
        code: 'MUR',
        name: 'الروبية الموريشيوسية',
        symbol: 'MUR',
        flag: '🇲🇺',
      ),
      Currency(
        code: 'MVR',
        name: 'الروفيا المالديفية',
        symbol: 'MVR',
        flag: '🇲🇻',
      ),
      Currency(
        code: 'MWK',
        name: 'الكواتشا الملاوي',
        symbol: 'MWK',
        flag: '🇲🇼',
      ),
      Currency(
        code: 'MXN',
        name: 'البيزو المكسيكي',
        symbol: 'MXN',
        flag: '🇲🇽',
      ),
      Currency(
        code: 'MYR',
        name: 'الرنجت الماليزي',
        symbol: 'MYR',
        flag: '🇲🇾',
      ),
      Currency(
        code: 'MZN',
        name: 'المتيكال الموزمبيقي',
        symbol: 'MZN',
        flag: '🇲🇿',
      ),
      Currency(
        code: 'NAD',
        name: 'دولار ناميبيا',
        symbol: 'NAD',
        flag: '🇳🇦',
      ),
      Currency(
        code: 'NGN',
        name: 'النيرة النيجيرية',
        symbol: 'NGN',
        flag: '🇳🇬',
      ),
      Currency(
        code: 'NIO',
        name: 'الكوردوبا النيكاراغوية',
        symbol: 'NIO',
        flag: '🇳🇮',
      ),
      Currency(
        code: 'NOK',
        name: 'الكرونا النرويجية',
        symbol: 'NOK',
        flag: '🇳🇴',
      ),
      Currency(
        code: 'NPR',
        name: 'الروبية النيبالية',
        symbol: 'NPR',
        flag: '🇳🇵',
      ),
      Currency(
        code: 'NZD',
        name: 'دولار نيوزيلندا',
        symbol: 'NZD',
        flag: '🇳🇿',
      ),
      Currency(
        code: 'OMR',
        name: 'الريال العماني',
        symbol: 'ر.ع',
        flag: '🇴🇲',
      ),
      Currency(
        code: 'PAB',
        name: 'البالبوا',
        symbol: 'PAB',
        flag: '🇵🇦',
      ),
      Currency(
        code: 'PEN',
        name: 'سول جديد',
        symbol: 'PEN',
        flag: '🇵🇪',
      ),
      Currency(
        code: 'PGK',
        name: 'كينا بابوا غينيا الجديدة',
        symbol: 'PGK',
        flag: '🇵🇬',
      ),
      Currency(
        code: 'PHP',
        name: 'البيسو الفلبيني',
        symbol: 'PHP',
        flag: '🇵🇭',
      ),
      Currency(
        code: 'PKR',
        name: 'الروبية الباكستانية',
        symbol: 'PKR',
        flag: '🇵🇰',
      ),
      Currency(
        code: 'PLN',
        name: 'الزلوتي البولندي',
        symbol: 'PLN',
        flag: '🇵🇱',
      ),
      Currency(
        code: 'PYG',
        name: 'الغوارني الباراغواي',
        symbol: 'PYG',
        flag: '🇵🇾',
      ),
      Currency(
        code: 'QAR',
        name: 'الريال القطري',
        symbol: 'ر.ق',
        flag: '🇶🇦',
      ),
      Currency(
        code: 'RON',
        name: 'الليو الروماني',
        symbol: 'RON',
        flag: '🇷🇴',
      ),
      Currency(
        code: 'RSD',
        name: 'الدينار الصربي',
        symbol: 'RSD',
        flag: '🇷🇸',
      ),
      Currency(
        code: 'RUB',
        name: 'الروبل الروسي',
        symbol: '₽',
        flag: '🇷🇺',
      ),
      Currency(
        code: 'RWF',
        name: 'الفرنك الروندي',
        symbol: 'RWF',
        flag: '🇷🇼',
      ),
      Currency(
        code: 'SAR',
        name: 'الريال السعودي',
        symbol: 'ر.س',
        flag: '🇸🇦',
      ),
      Currency(
        code: 'SCR',
        name: 'الروبية السيشيلية',
        symbol: 'SCR',
        flag: '🇸🇨',
      ),
      Currency(
        code: 'SDG',
        name: 'الجنيه السوداني',
        symbol: 'ج.س',
        flag: '🇸🇩',
      ),
      Currency(
        code: 'SEK',
        name: 'الكرونا السويدية',
        symbol: 'SEK',
        flag: '🇸🇪',
      ),
      Currency(
        code: 'SGD',
        name: 'دولار سنغافورة',
        symbol: 'SGD',
        flag: '🇸🇬',
      ),
      Currency(
        code: 'SOS',
        name: 'الشلن الصومالي',
        symbol: 'SOS',
        flag: '🇸🇴',
      ),
      Currency(
        code: 'STD',
        name: 'الدوبرا',
        symbol: 'STD',
        flag: '🇸🇹',
      ),
      Currency(
        code: 'SYP',
        name: 'الجنيه السوري',
        symbol: 'ل.س',
        flag: '🇸🇾',
      ),
      Currency(
        code: 'SZL',
        name: 'اللليلانجيني',
        symbol: 'SZL',
        flag: '🇸🇿',
      ),
      Currency(
        code: 'THB',
        name: 'البات التايلاندي',
        symbol: 'THB',
        flag: '🇹🇭',
      ),
      Currency(
        code: 'TJS',
        name: 'السوموني الطاجيكي',
        symbol: 'TJS',
        flag: '🇹🇯',
      ),
      Currency(
        code: 'TND',
        name: 'الدينار التونسي',
        symbol: 'د.ت',
        flag: '🇹🇳',
      ),
      Currency(
        code: 'TMT',
        name: 'المنات التركمانستاني',
        symbol: 'TMT',
        flag: '🇹🇲',
      ),
      Currency(
        code: 'TRY',
        name: 'الليرة التركية',
        symbol: '₺',
        flag: '🇹🇷',
      ),
      Currency(
        code: 'TTD',
        name: 'دولار ترينيداد وتوباغو',
        symbol: 'TTD',
        flag: '🇹🇹',
      ),
      Currency(
        code: 'TWD',
        name: 'دولار تايوان الجديد',
        symbol: 'TWD',
        flag: '🇹🇼',
      ),
      Currency(
        code: 'TZS',
        name: 'الشلن التنزاني',
        symbol: 'TZS',
        flag: '🇹🇿',
      ),
      Currency(
        code: 'UAH',
        name: 'الهريفنيا الأوكرانية',
        symbol: 'UAH',
        flag: '🇺🇦',
      ),
      Currency(
        code: 'UGX',
        name: 'الشلن الأوغندي',
        symbol: 'UGX',
        flag: '🇺🇬',
      ),
      Currency(
        code: 'UYU',
        name: 'البيزو الأوروغواي',
        symbol: 'UYU',
        flag: '🇺🇾',
      ),
      Currency(
        code: 'UZS',
        name: 'السوم الأوزبكي',
        symbol: 'UZS',
        flag: '🇺🇿',
      ),
      Currency(
        code: 'VEF',
        name: 'البوليفار الفنزويلي',
        symbol: 'VEF',
        flag: '🇻🇪',
      ),
      Currency(
        code: 'VES',
        name: 'البوليفار الفنزويلي السيادي',
        symbol: 'VES',
        flag: '🇻🇪',
      ),
      Currency(
        code: 'VND',
        name: 'الدونج الفيتنامي',
        symbol: '₫',
        flag: '🇻🇳',
      ),
      Currency(
        code: 'VUV',
        name: 'الفاتو',
        symbol: 'VUV',
        flag: '🇻🇺',
      ),
      Currency(
        code: 'XAF',
        name: 'فرنك الجماعة الاقتصادية والنقدية لوسط أفريقيا',
        symbol: 'XAF',
        flag: '🌍',
      ),
      Currency(
        code: 'XCD',
        name: 'دولار شرق الكاريبي',
        symbol: 'XCD',
        flag: '🏝️',
      ),
      Currency(
        code: 'XDR',
        name: 'حقوق السحب الخاصة',
        symbol: 'XDR',
        flag: '🏦',
      ),
      Currency(
        code: 'XOF',
        name: 'فرنك الجماعة المالية الأفريقية',
        symbol: 'XOF',
        flag: '🌍',
      ),
      Currency(
        code: 'XPF',
        name: 'فرنك بولينيزيا الفرنسية',
        symbol: 'XPF',
        flag: '🏝️',
      ),
      Currency(
        code: 'YER',
        name: 'الريال اليمني',
        symbol: 'ر.ي',
        flag: '🇾🇪',
      ),
      Currency(
        code: 'ZMK',
        name: 'الكواتشا الزامبي',
        symbol: 'ZMK',
        flag: '🇿🇲',
      ),
      Currency(
        code: 'ZAR',
        name: 'الراند الجنوب أفريقي',
        symbol: 'ZAR',
        flag: '🇿🇦',
      ),
      Currency(
        code: 'ZMW',
        name: 'الكواتشا الزامبي الجديد',
        symbol: 'ZMW',
        flag: '🇿🇲',
      ),
      Currency(
        code: 'ZWL',
        name: 'الدولار الزيمبابوي',
        symbol: 'ZWL',
        flag: '🇿🇼',
      ),
    ];
  }
}
